project:
  type: website
  output-dir: docs

website:
  favicon: favicon.png
  navbar:
    logo: logo.png
    background: dark
    search: true
    left:
      - text: "Home"
        href: index.qmd
      # - text: "Calendar"
      #   href: calendar.qmd
      - sidebar:syllabus
      # - text: "Project"
      #   href: project/project.qmd
      # - text: "Datasets"
      #   href: project/data.qmd
      - text: "Moodle Page"
        href: https://courses.furman.edu/course/view.php?id=23022
      - text: "Office Hours"
        href: syllabus/appointment.qmd
      - text: "Set an Appointment"
        href: https://calendly.com/ssultan-dpq/
  sidebar:
    - id: syllabus
      title: "Syllabus"
      background: light
      collapse-level: 1
      contents:
        - syllabus/about.qmd
        - syllabus/grading.qmd
        - syllabus/academic_success.md
        - syllabus/textbook.md
        - syllabus/integrity.md
        - syllabus/mental_health.md
        - syllabus/accomodations.md
        - syllabus/title_9.md
        - syllabus/aipolicy.qmd
    - id: content
      background: "#2d2d2d"
      style: "floating"
      search: true
      contents:
        - text: "Home"
          href: index.qmd
        - intro.qmd
        # - section: models.qmd
        #   contents:
        # - linearregression.md
        - linearregression.ipynb
        - section: snn.ipynb
          contents:
          - snn_multivariate.ipynb
          - snn_general.ipynb
          - snn_activations.ipynb
        - text: "Deep Neural Networks"
        - text: "Loss Functions"
        - text: "Gradient Descent"
        - text: "Back Propagation"
        - text: "Performance"
        - text: "Regularization"
        - text: "Transformers"
        - text: "Large Language Models"
        - text: "Diffusion Models"
        # - section: dnn.ipynb 
        #   contents:
        #   - dnn_clipping.ipynb
        #   - dnn_deep.ipynb
        # - section: loss.ipynb
        #   contents:
        #   - loss_regression.ipynb
        #   - loss_classification.ipynb
        #   - loss_multiclass.ipynb
        # - section: gradientdescent.ipynb
        #   contents:
        #   - gradientdescent_sgd.ipynb
        #   - gradientdescent_momentum.ipynb
        #   - gradientdescent_adam.ipynb
        #   - gradientdescent_linesearch.ipynb
        # - section: backprop.ipynb
        #   contents: 
        #   - backprop_algo.ipynb
        #   - backprop_init.ipynb
        #   - backprop_code.ipynb
        # - section: performance.ipynb
        #   contents: 
        #   - performance_biasvariance.ipynb
        #   - performance_doubledescent.ipynb
        #   - performance_highdimensions.ipynb
        # - section: transformers.ipynb
        #   contents:
        #   - transformers_multi.ipynb
        #   - transformers_nlp.ipynb
        #   - transformers_others.ipynb
        #   - transformers_decoding.ipynb
        # - section: llms.ipynb
        #   contents: 
        #   - llms_pretraining.ipynb
        #   - llms_finetuning.ipynb
        #   - llms_rlhf.ipynb
        # - unsupervised.md
        # - section: diffusion.ipynb
        #   contents: 
        #   - diffusion_encoder.ipynb 
        #   - diffusion_decoder.ipynb
        #   - diffusion_reparameterization.ipynb
        #   - diffusion_family.ipynb

format:
  html:
    theme:
      - darkly
      - custom.scss
    css: style.css
    toc: true
    # monobackgroundcolor: "#CCCCFF"
    monobackgroundcolor: "black"
    highlight-style: monokai #atom-one, github, dracula, monokai
    anchor-sections: true
    smooth-scroll: true
    # number-sections: true



